-- ============================================================
-- SHAKTI v2.0 — Deprecated Runtime Seed
-- ============================================================
--
-- This file intentionally performs no inserts.
-- Production and development environments must use the explicit
-- identity bootstrap flow instead of auto-seeded users, admins,
-- cases, or simulated operational data.
--
-- See:
--   npm run db:bootstrap-identities
-- and
--   database/bootstrap/officers-bootstrap.sql
--
SELECT 'seed.sql is intentionally a no-op; use controlled bootstrap flows.' AS notice;
