-- SHAKTI controlled officer bootstrap roster
-- This file contains baseline identity records only.
-- It must not contain case, evidence, upload, alert, or audit sample data.

INSERT INTO officers (
  buckle_id,
  full_name,
  phone_number,
  email,
  rank,
  position,
  department,
  station,
  is_active
)
VALUES
  ('BK-1001', 'Aarav Patel', '9876101001', 'constable01@police.gov.in', 'Constable', 'Constable', 'Telecom Investigation Unit', 'Ahmedabad Central', TRUE),
  ('BK-1002', 'Bhavesh Solanki', '9876101002', 'constable02@police.gov.in', 'Constable', 'Constable', 'Telecom Investigation Unit', 'Ahmedabad Central', TRUE),
  ('BK-1003', 'Chirag Rana', '9876101003', 'constable03@police.gov.in', 'Constable', 'Constable', 'Telecom Investigation Unit', 'Surat City', TRUE),
  ('BK-1004', 'Dhruv Parmar', '9876101004', 'constable04@police.gov.in', 'Constable', 'Constable', 'Telecom Investigation Unit', 'Surat City', TRUE),
  ('BK-1005', 'Eshan Chaudhary', '9876101005', 'constable05@police.gov.in', 'Constable', 'Constable', 'Telecom Investigation Unit', 'Rajkot Urban', TRUE),
  ('BK-1006', 'Farhan Sheikh', '9876101006', 'constable06@police.gov.in', 'Constable', 'Constable', 'Telecom Investigation Unit', 'Rajkot Urban', TRUE),
  ('BK-1007', 'Gaurav Joshi', '9876101007', 'constable07@police.gov.in', 'Constable', 'Constable', 'Telecom Investigation Unit', 'Vadodara City', TRUE),
  ('BK-1008', 'Harsh Mehta', '9876101008', 'constable08@police.gov.in', 'Constable', 'Constable', 'Telecom Investigation Unit', 'Vadodara City', TRUE),
  ('BK-1009', 'Ishaan Thakur', '9876101009', 'constable09@police.gov.in', 'Constable', 'Constable', 'Telecom Investigation Unit', 'Bhavnagar', TRUE),
  ('BK-1010', 'Jignesh Vyas', '9876101010', 'constable10@police.gov.in', 'Constable', 'Constable', 'Telecom Investigation Unit', 'Bhavnagar', TRUE),
  ('BK-1011', 'Karan Chauhan', '9876101011', 'headconstable01@police.gov.in', 'Head Constable', 'Head Constable', 'Telecom Investigation Unit', 'Ahmedabad Central', TRUE),
  ('BK-1012', 'Laksh Shah', '9876101012', 'headconstable02@police.gov.in', 'Head Constable', 'Head Constable', 'Telecom Investigation Unit', 'Ahmedabad Central', TRUE),
  ('BK-1013', 'Manish Trivedi', '9876101013', 'headconstable03@police.gov.in', 'Head Constable', 'Head Constable', 'Telecom Investigation Unit', 'Surat City', TRUE),
  ('BK-1014', 'Nikhil Desai', '9876101014', 'headconstable04@police.gov.in', 'Head Constable', 'Head Constable', 'Telecom Investigation Unit', 'Surat City', TRUE),
  ('BK-1015', 'Omkar Yadav', '9876101015', 'headconstable05@police.gov.in', 'Head Constable', 'Head Constable', 'Telecom Investigation Unit', 'Rajkot Urban', TRUE),
  ('BK-1016', 'Pranav Gohil', '9876101016', 'headconstable06@police.gov.in', 'Head Constable', 'Head Constable', 'Telecom Investigation Unit', 'Rajkot Urban', TRUE),
  ('BK-1017', 'Qasim Mansuri', '9876101017', 'headconstable07@police.gov.in', 'Head Constable', 'Head Constable', 'Telecom Investigation Unit', 'Vadodara City', TRUE),
  ('BK-1018', 'Rohan Bhatt', '9876101018', 'headconstable08@police.gov.in', 'Head Constable', 'Head Constable', 'Telecom Investigation Unit', 'Vadodara City', TRUE),
  ('BK-1019', 'Sagar Pandya', '9876101019', 'headconstable09@police.gov.in', 'Head Constable', 'Head Constable', 'Telecom Investigation Unit', 'Bhavnagar', TRUE),
  ('BK-1020', 'Tushar Makwana', '9876101020', 'headconstable10@police.gov.in', 'Head Constable', 'Head Constable', 'Telecom Investigation Unit', 'Bhavnagar', TRUE),
  ('BK-1021', 'Uday Rathod', '9876101021', 'asi01@police.gov.in', 'Assistant Sub-Inspector', 'Assistant Sub-Inspector', 'Telecom Investigation Unit', 'Ahmedabad Central', TRUE),
  ('BK-1022', 'Vikas Modi', '9876101022', 'asi02@police.gov.in', 'Assistant Sub-Inspector', 'Assistant Sub-Inspector', 'Telecom Investigation Unit', 'Ahmedabad Central', TRUE),
  ('BK-1023', 'Waseem Khan', '9876101023', 'asi03@police.gov.in', 'Assistant Sub-Inspector', 'Assistant Sub-Inspector', 'Telecom Investigation Unit', 'Surat City', TRUE),
  ('BK-1024', 'Yash Soni', '9876101024', 'asi04@police.gov.in', 'Assistant Sub-Inspector', 'Assistant Sub-Inspector', 'Telecom Investigation Unit', 'Surat City', TRUE),
  ('BK-1025', 'Zuber Mirza', '9876101025', 'asi05@police.gov.in', 'Assistant Sub-Inspector', 'Assistant Sub-Inspector', 'Telecom Investigation Unit', 'Rajkot Urban', TRUE),
  ('BK-1026', 'Amit Jhala', '9876101026', 'asi06@police.gov.in', 'Assistant Sub-Inspector', 'Assistant Sub-Inspector', 'Telecom Investigation Unit', 'Rajkot Urban', TRUE),
  ('BK-1027', 'Bharat Chavda', '9876101027', 'asi07@police.gov.in', 'Assistant Sub-Inspector', 'Assistant Sub-Inspector', 'Telecom Investigation Unit', 'Vadodara City', TRUE),
  ('BK-1028', 'Chetan Amin', '9876101028', 'asi08@police.gov.in', 'Assistant Sub-Inspector', 'Assistant Sub-Inspector', 'Telecom Investigation Unit', 'Vadodara City', TRUE),
  ('BK-1029', 'Devendra Kothari', '9876101029', 'asi09@police.gov.in', 'Assistant Sub-Inspector', 'Assistant Sub-Inspector', 'Telecom Investigation Unit', 'Bhavnagar', TRUE),
  ('BK-1030', 'Firoz Saiyed', '9876101030', 'asi10@police.gov.in', 'Assistant Sub-Inspector', 'Assistant Sub-Inspector', 'Telecom Investigation Unit', 'Bhavnagar', TRUE),
  ('BK-1031', 'Girish Purohit', '9876101031', 'si01@police.gov.in', 'Sub-Inspector', 'Sub-Inspector', 'Telecom Investigation Unit', 'Ahmedabad Central', TRUE),
  ('BK-1032', 'Hitesh Nair', '9876101032', 'si02@police.gov.in', 'Sub-Inspector', 'Sub-Inspector', 'Telecom Investigation Unit', 'Ahmedabad Central', TRUE),
  ('BK-1033', 'Imran Qureshi', '9876101033', 'si03@police.gov.in', 'Sub-Inspector', 'Sub-Inspector', 'Telecom Investigation Unit', 'Surat City', TRUE),
  ('BK-1034', 'Jayesh Barot', '9876101034', 'si04@police.gov.in', 'Sub-Inspector', 'Sub-Inspector', 'Telecom Investigation Unit', 'Surat City', TRUE),
  ('BK-1035', 'Kishan Vadher', '9876101035', 'si05@police.gov.in', 'Sub-Inspector', 'Sub-Inspector', 'Telecom Investigation Unit', 'Rajkot Urban', TRUE),
  ('BK-1036', 'Mahesh Padhiyar', '9876101036', 'si06@police.gov.in', 'Sub-Inspector', 'Sub-Inspector', 'Telecom Investigation Unit', 'Rajkot Urban', TRUE),
  ('BK-1037', 'Nirav Kakkad', '9876101037', 'si07@police.gov.in', 'Sub-Inspector', 'Sub-Inspector', 'Telecom Investigation Unit', 'Vadodara City', TRUE),
  ('BK-1038', 'Parth Vora', '9876101038', 'si08@police.gov.in', 'Sub-Inspector', 'Sub-Inspector', 'Telecom Investigation Unit', 'Vadodara City', TRUE),
  ('BK-1039', 'Ritesh Dholakia', '9876101039', 'si09@police.gov.in', 'Sub-Inspector', 'Sub-Inspector', 'Telecom Investigation Unit', 'Bhavnagar', TRUE),
  ('BK-1040', 'Soham Kapadia', '9876101040', 'si10@police.gov.in', 'Sub-Inspector', 'Sub-Inspector', 'Telecom Investigation Unit', 'Bhavnagar', TRUE),
  ('BK-1041', 'Tanmay Dave', '9876101041', 'inspector01@police.gov.in', 'Inspector', 'Inspector', 'Telecom Investigation Unit', 'Ahmedabad Central', TRUE),
  ('BK-1042', 'Umang Baxi', '9876101042', 'inspector02@police.gov.in', 'Inspector', 'Inspector', 'Telecom Investigation Unit', 'Ahmedabad Central', TRUE),
  ('BK-1043', 'Viral Rawal', '9876101043', 'inspector03@police.gov.in', 'Inspector', 'Inspector', 'Telecom Investigation Unit', 'Surat City', TRUE),
  ('BK-1044', 'Yatin Suthar', '9876101044', 'inspector04@police.gov.in', 'Inspector', 'Inspector', 'Telecom Investigation Unit', 'Surat City', TRUE),
  ('BK-1045', 'Zalak Pandit', '9876101045', 'inspector05@police.gov.in', 'Inspector', 'Inspector', 'Telecom Investigation Unit', 'Rajkot Urban', TRUE),
  ('BK-1046', 'Ankit Limbachiya', '9876101046', 'inspector06@police.gov.in', 'Inspector', 'Inspector', 'Telecom Investigation Unit', 'Rajkot Urban', TRUE),
  ('BK-1047', 'Bhavin Parmar', '9876101047', 'inspector07@police.gov.in', 'Inspector', 'Inspector', 'Telecom Investigation Unit', 'Vadodara City', TRUE),
  ('BK-1048', 'Chaitanya Dodiya', '9876101048', 'inspector08@police.gov.in', 'Inspector', 'Inspector', 'Telecom Investigation Unit', 'Vadodara City', TRUE),
  ('BK-1049', 'Darshan Bhuva', '9876101049', 'inspector09@police.gov.in', 'Inspector', 'Inspector', 'Telecom Investigation Unit', 'Bhavnagar', TRUE),
  ('BK-1050', 'Ekta Trivedi', '9876101050', 'inspector10@police.gov.in', 'Inspector', 'Inspector', 'Telecom Investigation Unit', 'Bhavnagar', TRUE)
ON CONFLICT (buckle_id) DO UPDATE
SET
  full_name = EXCLUDED.full_name,
  phone_number = EXCLUDED.phone_number,
  email = EXCLUDED.email,
  rank = EXCLUDED.rank,
  position = EXCLUDED.position,
  department = EXCLUDED.department,
  station = EXCLUDED.station,
  is_active = EXCLUDED.is_active,
  updated_at = NOW();
